spring.application.name=soap
spring.sql.init.mode=always
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/db_soap?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=torresmunoz1